version: 2
updates:
  # Maintain dependencies for NPM
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    assignees:
      - "a-rustacean"
    reviewers:
      - "a-rustacean"
